linters:
  enable:
    - revive
    - goimports
    - gofmt
    - asasalint
    - bidichk
    - copyloopvar
    - errcheck
    - misspell
    #- cyclop
    
linters-settings:
  revive:
    # Maximum number of open files at the same time.
    # See https://github.com/mgechev/revive#command-line-flags
    # Defaults to unlimited.
    max-open-files: 2048

    # When set to false, ignores files with "GENERATED" header, similar to golint.
    # See https://github.com/mgechev/revive#available-rules for details.
    # Default: false
    ignore-generated-header: true

    # Sets the default severity.
    # See https://github.com/mgechev/revive#configuration
    # Default: warning
    severity: warning

    # Enable all available rules.
    # Default: false
    enable-all-rules: false

    # Sets the default failure confidence.
    # This means that linting errors with less than 0.8 confidence will be ignored.
    # Default: 0.8
    confidence: 0.1

    rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#empty-lines
      - name: empty-lines
        severity: warning
        disabled: false
        exclude: [""]
issues:
  exclude-files:
    - internal/templates/files.go
    - mocks/*
    - test/*
  exclude:
    - SA1019 # FIX: replace EndpointResolver and EndpointResolverWithOptions with EndpointResolverV2 and BaseEndpoint.
  include:
    - EXC0012 # revive: Annoying issue about not having a comment. The rare codebase has such comments
      # - exported (.+) should have comment( \(or a comment on this block\))? or be unexported
    - EXC0014 # revive: Annoying issue about not having a comment. The rare codebase has such comments
      # - comment on exported (.+) should be of the form "(.+)..."
